### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by matthewjessee16** [yumi-modding/FS22_additionalFieldInfo#4]
when i start a game with precision farming and additional field info, additional field info doesnt give me the field size in the field info box.

**Comment by matthewjessee16** [comment]
Did yumi not fix this mod?

**Comment by yumi-modding** [comment]
Hello
I made a quick check and I think field size is missing, only land size is displayed.
The thing is I thought i saw this info already displayed with precision Farming.
I will fix this

**Comment by matthewjessee16** [comment]
Okay, the thing is that it doesn’t seem to work at all

**Comment by matthewjessee16** [comment]
When ever I have precision farming installed additional field info just stops working

**Comment by yumi-modding** [comment]
It was true for first modhub release but then i fixed some code

**Comment by matthewjessee16** [comment]
It still doesn’t work though

**Comment by matthewjessee16** [comment]
Do you want my log?
